import test from 'node:test';import assert from 'node:assert/strict';
import {createProject,parseProject,projectV5Schema,newId} from '../src/domain/model.ts';
import {importManifest,addPending,addFamily,editBinding,suggestions,exportRevit,toRevitPosition,effectiveParameters} from '../src/revit/operations.ts';
import {serializeProject,deserializeProject} from '../src/persistence/serialization.ts';
import {translateEntity,rotateEntity,hideEntity,joinObjects} from '../src/domain/groups.ts';
import {copyEntity,pasteEntity} from '../src/domain/clipboard.ts';
import {readRfa} from '../src/revit/files.ts';
const family={id:'fixture-desk',name:'Escritorio de prueba de contrato',category:'escritorios',revitCategory:'Furniture',fileName:'fixture.rfa',sourcePath:'C:\\Families\\fixture.rfa',status:'processed',revitVersion:'2026',placement:'free',unit:'cm',originalBase64:null,thumbnail:null,types:[{id:'120',name:'120 cm',dimensionsCm:{width:120,depth:60,height:75},dimensionParameters:{width:'type:Width',depth:null,height:null},parameters:[{key:'type:Width',name:'Width',scope:'type',storage:'double',unit:'cm',readOnly:false,value:120},{key:'instance:Code',name:'Code',scope:'instance',storage:'string',unit:'text',readOnly:false,value:'A'}]}],notes:['Synthetic test fixture; not extracted from a real RFA.']};
const manifest={format:'habitacion.revit-families',version:1,families:[family]};
const dims={width:120,depth:60,height:75,x:100,y:100,z:10,wallId:'north',offset:50};
test('V5 collection content migrates to current V10 without modifying old dimensions or objects',()=>{const {families,...old}=createProject();old.schemaVersion=5;delete old.assets;delete old.room.fixedVolumes;projectV5Schema.parse(old);const next=parseProject(old);assert.deepEqual(next,{...old,schemaVersion:11,assets:[],families:[],room:{...old.room,fixedVolumes:[]}});assert.equal(old.schemaVersion,5);});
test('RFA originals survive JSON and cannot be placed before processing',async()=>{const bytes=new Uint8Array([0xd0,0xcf,0x11,0xe0,0xa1,0xb1,0x1a,0xe1,1]);const raw=await readRfa(new File([bytes],'contract.rfa'));const p=addPending(createProject(),'contract.rfa',raw);assert.equal(deserializeProject(serializeProject(p)).families[0].originalBase64,raw);assert.throws(()=>addFamily(p,p.families[0].id,'x',dims,{}));await assert.rejects(readRfa(new File([bytes],'bad.raf')));await assert.rejects(readRfa(new File(['not a family'],'bad.rfa')));});
test('family binding parameters originals and dimensions survive all object operations and Revit exchange',()=>{let p=importManifest(createProject(),manifest);const result=addFamily(p,family.id,'120',dims,{'instance:Code':'B'});p=result.project;const id=result.id;const copy=pasteEntity(p,copyEntity(p,id));p=joinObjects(copy.project,[id,copy.selected],'Revit set');p=hideEntity(rotateEntity(translateEntity(p,id,20,30,40),id,15),id,true);const decoded=deserializeProject(JSON.stringify(exportRevit(p)));assert.deepEqual(decoded,p);assert.equal(decoded.objects[0].revit.parameters['instance:Code'],'B');assert.equal(decoded.objects[1].revit.familyId,family.id);assert.equal(decoded.objects[0].dimensions.width.manualCm,120);assert.equal(decoded.objects[0].hidden,true);assert.equal(effectiveParameters(family,decoded.objects[0].revit,{width:140,depth:60,height:75})['type:Width'],140);assert.throws(()=>editBinding(p,id,{familyId:family.id,typeId:'missing',parameters:{}}));assert.throws(()=>editBinding(p,id,{familyId:family.id,typeId:'120',parameters:{'type:Width':'bad'}}));});
test('door families stay structural and retain identity through moves and exchange',()=>{const f={...family,id:'door-fixture',category:'puertas',placement:'wall'},p=importManifest(createProject(),{...manifest,families:[f]}),next=addFamily(p,f.id,'120',{...dims,width:90,height:200,z:0},{});assert.equal(next.structural,true);assert.equal(next.project.objects.length,0);assert.equal(next.project.room.fixedElements[0].revit.familyId,f.id);assert.deepEqual(deserializeProject(serializeProject(next.project)),next.project);});
test('suggestions never mutate project and only point to imported processed families',()=>{const p=importManifest(createProject(),manifest),before=serializeProject(p),s=suggestions(p,'habitación con zona de estudio');assert.ok(s.some(s=>s.category==='escritorios'&&s.families.length===1));assert.equal(serializeProject(p),before);const placed=addFamily(p,family.id,'120',dims,{}).project;assert.ok(!suggestions(placed,'zona de estudio').some(s=>s.category==='escritorios'));});
test('centimeters and screen Y convert to Revit feet with unchanged vertical sign',()=>{assert.deepEqual(toRevitPosition({x:30.48,y:60.96,z:91.44}),{x:1,y:-2,z:3});});

test('8 MB RFA validates without regex stack overflow and rejects malformed base64',()=>{const raw=Buffer.alloc(8_000_000).toString('base64');const p=addPending(createProject(),'large.rfa',raw);assert.equal(p.families[0].originalBase64.length,raw.length);assert.throws(()=>addPending(createProject(),'bad.rfa','ab='));assert.throws(()=>addPending(createProject(),'bad.rfa','===='));});
