import test from 'node:test';import assert from 'node:assert/strict';
import {createProject,setManualDimensions} from '../src/domain/model.ts';
import {initialCollection,parseCollection,addRoom,duplicateRoom,namedProject,removeRoom} from '../src/domain/rooms.ts';
test('legacy migration keeps existing room and manual measurements untouched',()=>{const p=setManualDimensions(createProject(),{width:420,depth:380,height:270}),before=structuredClone(p),c=initialCollection(p);assert.deepEqual(c.projects[0],before);assert.equal(c.activeId,p.id);assert.deepEqual(p,before);assert.throws(()=>initialCollection({...p,schemaVersion:99}));});
test('independent rooms duplicate rename switch delete and JSON persistence',()=>{const a=createProject(),b=duplicateRoom(a,'Otra');let c=addRoom(initialCollection(a),b);assert.notEqual(a.id,b.id);assert.notEqual(a.room.id,b.room.id);b.room.dimensions.width.manualCm=500;assert.equal(a.room.dimensions.width.manualCm,null);c={...c,projects:c.projects.map(p=>p.id===b.id?namedProject(p,'Dormitorio'):p)};assert.equal(c.projects[0].name,a.name);assert.equal(c.projects[1].name,'Dormitorio');assert.deepEqual(parseCollection(JSON.parse(JSON.stringify(c))),c);const deleted=removeRoom(c,b.id);assert.equal(deleted.activeId,a.id);assert.throws(()=>removeRoom(deleted,a.id));assert.throws(()=>parseCollection({...c,activeId:createProject().id}));assert.throws(()=>addRoom(c,a));assert.throws(()=>namedProject(a,'  '));});
import {newId,upsertObject} from '../src/domain/model.ts';
import {joinObjects} from '../src/domain/groups.ts';
import {translateSelection,entitySelection} from '../src/domain/selection.ts';
test('multi-selection moves each grouped piece once and preserves real dimensions',()=>{const m=n=>({defaultCm:n,manualCm:n,estimatedCm:null});const box=x=>({id:newId(),name:'Mesa',category:'Mueble',initialHeightCm:80,hidden:false,groupId:null,position:{x,y:100,z:0},rotationDeg:0,dimensions:{width:m(60),depth:m(40),height:m(80)},model:{kind:'box',source:'manual-approximation'},material:{color:'#557799',textureId:null},photoIds:[]});const a=box(100),b=box(180),c=box(250);const p=joinObjects([a,b,c].reduce(upsertObject,createProject()),[a.id,b.id],'Grupo');const next=translateSelection(p,[a.id,b.id,c.id],20,10,30);assert.equal(entitySelection(p,[a.id,b.id,c.id]).length,2);for(let i=0;i<3;i++){assert.equal(next.objects[i].position.x,p.objects[i].position.x+20);assert.equal(next.objects[i].position.z,30);assert.deepEqual(next.objects[i].dimensions,p.objects[i].dimensions);}});
