 'use client';
import {Eye,EyeOff,CheckSquare,Layers,Search} from 'lucide-react';
import {ObjectThumbnail} from '../rendering/ObjectThumbnail';
import {ObjectTransform} from './ObjectTransform';
import {PartsEditor} from './PartsEditor';
import {templateNames,templateParts,type Template} from '../domain/templates.ts';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {newId,upsertObject,validationMessage,effectiveDimensions,type Project} from '../domain/model.ts';
import {cm,type MovableObject} from '../domain/objects.ts';
import {resetInitialHeight,members,entityBounds,joinObjects,ungroup,translateEntity,rotateEntity,hideEntity,deleteEntity} from '../domain/groups.ts';
import {collisionWarnings} from '../collisions/objects.ts';
import {HeightControl} from './HeightControl';
import {CoordinateGuide} from './CoordinateGuide';
export function ObjectsPanel({project,selected,onSelect,onChange,checked,onChecked,showList=true}:{checked:string[];onChecked:(ids:string[])=>void;showList?:boolean;project:Project;selected:string|null;onSelect:(id:string|null)=>void;onChange:(p:Project)=>void}){
 const [query,setQuery]=useState(''),[multi,setMulti]=useState(false);
 const [editing,setEditing]=useState<MovableObject|null|undefined>(undefined),[error,setError]=useState(''),[groupName,setGroupName]=useState('Mi conjunto');
 const active=project.objects.find(o=>o.id===selected),group=project.groups.find(g=>g.id===active?.groupId),parts=active?members(project,active.id):[],bounds=active?entityBounds(project,active.id):null,d=effectiveDimensions(project.room),warnings=collisionWarnings(project.room,project.objects);
 const rows=project.objects.filter((o,i,all)=>!o.groupId||all.findIndex(b=>b.groupId===o.groupId)===i);
 function apply(fn:()=>Project){try{onChange(fn());setError('');}catch(e){setError(validationMessage(e));}}
 return <section className="structure-panel objects-panel">{showList&&<><div className="object-list-toolbar"><label className="object-search"><Search size={16}/><Input aria-label="Buscar objetos de la habitación" placeholder="Buscar objeto" value={query} onChange={e=>setQuery(e.target.value)}/></label><Button variant={multi?'secondary':'ghost'} size="icon" aria-label="Seleccionar varios objetos" aria-pressed={multi} onClick={()=>setMulti(!multi)}><CheckSquare/></Button></div>
 <ul className="object-gallery">{rows.filter(o=>(project.groups.find(g=>g.id===o.groupId)?.name??o.name).toLowerCase().includes(query.toLowerCase())).map(o=>{const g=project.groups.find(g=>g.id===o.groupId),all=members(project,o.id),hidden=all.every(o=>o.hidden),warning=all.some(o=>warnings.has(o.id)),name=g?.name??o.name;return <li key={o.id} className={`object-tile ${parts.some(b=>b.id===o.id)?'is-selected':''} ${hidden?'is-hidden':''} ${warning?'has-warning':''}`}>
 <button className="object-tile-select" aria-label={`Editar ${name}`} aria-pressed={parts.some(b=>b.id===o.id)} onClick={()=>onSelect(o.id)}><ObjectThumbnail objects={all}/><strong>{name}</strong><span>{g?`${all.length} piezas`: `${cm(o.dimensions.width)} × ${cm(o.dimensions.depth)} × ${cm(o.dimensions.height)} cm`}</span></button>
 <div className="object-tile-tools">{multi&&<Checkbox aria-label={`Incluir ${name} en unión`} checked={checked.includes(o.id)} onCheckedChange={v=>onChecked(v?[...checked,o.id]:checked.filter(id=>id!==o.id))}/>}<span>{warning?'Colisión':hidden?'Oculto':g?<Layers size={16}/>:null}</span><Button size="icon" variant="ghost" aria-label={`${hidden?'Mostrar':'Ocultar'} ${name}`} title={hidden?'Mostrar':'Ocultar'} onClick={()=>apply(()=>hideEntity(project,o.id,!hidden))}>{hidden?<EyeOff aria-hidden="true"/>:<Eye aria-hidden="true"/>}</Button></div></li>;})}</ul>{!rows.length&&<p className="object-empty">Tu habitación está vacía. Añade un mueble para empezar.</p>}</>}
 {checked.length>1&&<><label htmlFor="group-name">Nombre del conjunto</label><Input id="group-name" value={groupName} onChange={e=>setGroupName(e.target.value)}/><Button variant="outline" disabled={checked.filter(id=>project.objects.some(o=>o.id===id)).length<2} onClick={()=>apply(()=>{const next=joinObjects(project,checked,groupName);onSelect(checked[0]);onChecked([]);return next;})}>Unir seleccionados</Button></>}
 {(!active||showList)&&<Button className="custom-object-button" variant="outline" onClick={()=>setEditing(null)} disabled={project.objects.length>=100}>Crear objeto a medida</Button>}
 {active&&bounds&&<div className="object-actions"><h3>{group?.name??active.name}</h3><p>X {bounds.x.toFixed(1)} · Y {bounds.y.toFixed(1)} · Z {bounds.z.toFixed(1)} cm{group?' · Conjunto':` · ${active.rotationDeg}°`}</p><ObjectTransform key={`${active.id}-${project.updatedAt}`} project={project} object={active} onChange={onChange}/>
 {group?<><Button variant="outline" onClick={()=>apply(()=>ungroup(project,active.id))}>Separar conjunto</Button>{parts.map(o=><Button key={o.id} variant="outline" onClick={()=>setEditing(o)}>Editar pieza {o.name}</Button>)}</>:<Button variant="outline" onClick={()=>setEditing(active)}>Editar objeto</Button>}
 <PartsEditor key={active.id} project={project} object={active} onChange={onChange}/>{[15,45,90].map(angle=><Button key={angle} variant="outline" onClick={()=>apply(()=>rotateEntity(project,active.id,angle))}>Girar {angle}°</Button>)}<Button variant="destructive" onClick={()=>apply(()=>{const next=deleteEntity(project,active.id);onSelect(null);return next;})}>Eliminar {group?'conjunto':'objeto'}</Button>
 <details className="height-details"><summary>Altura y ajustes avanzados</summary><Button variant="outline" onClick={()=>apply(()=>resetInitialHeight(project,active.id))}>Restaurar alto inicial</Button><HeightControl label={group?'Base Z del conjunto':'Base Z'} value={bounds.z} max={d.height} onChange={z=>apply(()=>translateEntity(project,active.id,0,0,z-bounds.z))}/><Button variant="outline" onClick={()=>apply(()=>translateEntity(project,active.id,0,0,-bounds.z))}>Apoyar en el suelo</Button>
 {!group&&<HeightControl label="Alto del objeto" min={1} value={cm(active.dimensions.height)} max={d.height} onChange={height=>apply(()=>upsertObject(project,{...active,dimensions:{...active.dimensions,height:{...active.dimensions.height,manualCm:height}}}))}/>}
 {!group&&active.model.kind==='compound'&&<p className="helper">El alto general y Restaurar alto inicial escalan las piezas proporcionalmente. Para mantener grosores, edita cada pieza en Forma y colisiones.</p>}
 </details>
 {parts.flatMap(o=>(warnings.get(o.id)??[]).map(w=><p className="error-message" key={o.id+w}>{o.name}: {w}</p>))}
 </div>}
 <details><summary>Sobre ocultación y conjuntos</summary><p className="helper">Ocultar retira el objeto de ambas vistas; sigue contando en las colisiones. Un conjunto conserva las medidas y formas de sus piezas.</p></details>
 {error&&<p role="alert" className="error-message">{error}</p>}
 <Dialog open={editing!==undefined} onOpenChange={open=>{if(!open)setEditing(undefined);}}><DialogContent className="opening-dialog"><DialogTitle>{editing?'Editar objeto':'Añadir objeto'}</DialogTitle><DialogDescription>Volumen aproximado. Las colisiones avisan, pero no impiden guardarlo.</DialogDescription>{editing!==undefined&&<ObjectForm project={project} object={editing} onSave={(p,id)=>{onChange(p);onSelect(id);setEditing(undefined);setError('');}}/>}</DialogContent></Dialog></section>;
}
function ObjectForm({project,object,onSave}:{project:Project;object:MovableObject|null;onSave:(p:Project,id:string)=>void}){
 const [template,setTemplate]=useState<Template|'box'>('box');
 const [name,setName]=useState(object?.name??''),[category,setCategory]=useState(object?.category??'Mueble'),[color,setColor]=useState(object?.material.color??'#557799'),[error,setError]=useState('');
 const initial={width:object?String(cm(object.dimensions.width)):'',depth:object?String(cm(object.dimensions.depth)):'',height:object?String(cm(object.dimensions.height)):'',x:String(object?.position.x??100),y:String(object?.position.y??100),z:String(object?.position.z??0),rotation:String(object?.rotationDeg??0)};
 const [values,setValues]=useState(initial),[touched,setTouched]=useState<Partial<Record<keyof typeof initial,boolean>>>({});
 const labels={width:'Ancho del objeto',depth:'Fondo del objeto',height:'Alto del objeto',x:'Centro X',y:'Centro Y',z:'Base Z',rotation:'Giro en grados'};
 function save(e:React.FormEvent){e.preventDefault();try{
  const n={} as Record<keyof typeof initial,number>;for(const k of Object.keys(values) as (keyof typeof initial)[]){if(!/^-?\d+(?:[.,]\d+)?$/.test(values[k].trim()))throw new Error(`${labels[k]}: introduce un número válido.`);n[k]=Number(values[k].replace(',','.'));}
  const measure=(k:'width'|'depth'|'height')=>object&&!touched[k]?object.dimensions[k]:{defaultCm:n[k],estimatedCm:object?.dimensions[k].estimatedCm??null,manualCm:n[k]};
  const o:MovableObject={...(object?.revit?{revit:object.revit}:{}),id:object?.id??newId(),initialHeightCm:object?.initialHeightCm??n.height,hidden:object?.hidden??false,groupId:object?.groupId??null,name,category,position:{x:n.x,y:n.y,z:n.z},rotationDeg:n.rotation,dimensions:{width:measure('width'),depth:measure('depth'),height:measure('height')},model:object?.model??(template==='box'?{kind:'box',source:'manual-approximation'}:{kind:'compound',source:'manual-approximation',parts:templateParts(template)}),material:{color,textureId:null},photoIds:[]};onSave(upsertObject(project,o),o.id);
 }catch(e){setError(validationMessage(e));}}
 return <form onSubmit={save} className="measure-form"><details><summary>Ayuda con medidas y coordenadas</summary><CoordinateGuide room={project.room}/></details>{!object&&<label>Forma inicial<NativeSelect aria-label="Forma inicial" value={template} onChange={e=>{const key=e.target.value as Template|'box';setTemplate(key);if(key!=='box'){if(!name)setName(templateNames[key]);setCategory(templateNames[key]);}}}><NativeSelectOption value="box">Caja simple</NativeSelectOption>{Object.entries(templateNames).map(([k,v])=><NativeSelectOption key={k} value={k}>{v}</NativeSelectOption>)}</NativeSelect><p className="helper">Introduce las medidas exteriores reales; después ajusta cada pieza en Forma y colisiones.</p></label>}{object?.model.kind==='compound'&&<p className="helper">Cambiar ancho, fondo o alto escala todas las piezas proporcionalmente. Para ajustar solo una parte usa Forma y colisiones.</p>}<label htmlFor="object-name">Nombre</label><Input id="object-name" value={name} onChange={e=>setName(e.target.value)} required/><label htmlFor="object-category">Categoría</label><Input id="object-category" value={category} onChange={e=>setCategory(e.target.value)} required/>
 <div className="object-fields">{(Object.keys(labels) as (keyof typeof initial)[]).map(k=><div key={k}><label htmlFor={`object-${k}`}>{labels[k]}{k==='rotation'?'':' (cm)'}</label><Input id={`object-${k}`} inputMode="decimal" value={values[k]} onChange={e=>{setValues({...values,[k]:e.target.value});setTouched({...touched,[k]:true});}} required/></div>)}</div><details className="quick-height"><summary>Ajustar altura con deslizadores</summary><HeightControl label="Base Z rápida" value={Number(values.z.replace(',','.'))||0} max={effectiveDimensions(project.room).height} onChange={n=>{setValues({...values,z:String(n)});setTouched({...touched,z:true});}}/><HeightControl label="Alto rápido" min={1} value={Number(values.height.replace(',','.'))||1} max={effectiveDimensions(project.room).height} onChange={n=>{setValues({...values,height:String(n)});setTouched({...touched,height:true});}}/></details><label htmlFor="object-color">Color</label><Input id="object-color" type="color" value={color} onChange={e=>setColor(e.target.value)}/><p className="helper">X/Y son el centro del objeto. Z es la altura de su base sobre el suelo.</p>{error&&<p role="alert" className="error-message">{error}</p>}<Button type="submit">Guardar objeto</Button></form>;
}
