'use client';
import {useMemo,useRef,useState} from 'react';
import {Bed,Armchair,DoorOpen,AppWindow,Box,Columns3,Table2,Fan,RectangleVertical,LibraryBig} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {presets,addPreset} from '../domain/presets.ts';
import {createProject} from '../domain/model.ts';
import {ObjectThumbnail} from '../rendering/ObjectThumbnail';
const icons={bed:Bed,chair:Armchair,door:DoorOpen,window:AppWindow,pillar:Columns3,table:Table2,desk:Table2,fan:Fan,radiator:RectangleVertical,wardrobe:LibraryBig,shelf:LibraryBig,custom:Box};
export function PresetLibrary({onAdd,onClose,onPlace}:{onPlace:(key:string,x:number,y:number)=>void;onAdd:(key:string)=>void;onClose:()=>void}){
 const previews=useMemo(()=>Object.fromEntries(presets.filter(p=>p.kind==='movable').map(p=>[p.key,addPreset(createProject(),p.key,0,0).project.objects])),[]);
 const drag=useRef<{key:string;x:number;y:number}|null>(null),moved=useRef(false);const [ghost,setGhost]=useState<{x:number;y:number;name:string}|null>(null);
 return <aside className="preset-library" aria-label="Biblioteca de elementos"><header><h2>Añadir objeto</h2><Button variant="ghost" onClick={onClose}>Cerrar</Button></header><p>Arrastra al plano o pulsa para añadir. Medidas de ejemplo, editables.</p>{[['movable','Muebles'],['opening','Puertas y ventanas'],['fixed','Elementos fijos']].map(([kind,label])=><section key={kind}><h3>{label}</h3><div className="preset-grid">{presets.filter(p=>p.kind===kind).map(p=>{const Icon=icons[p.key];return <Button key={p.key} variant="outline" className="preset-card" style={{touchAction:'none'}} onPointerDown={e=>{if(e.button!==0)return;drag.current={key:p.key,x:e.clientX,y:e.clientY};moved.current=false;e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!drag.current)return;if(Math.hypot(e.clientX-drag.current.x,e.clientY-drag.current.y)>6){moved.current=true;setGhost({x:e.clientX,y:e.clientY,name:p.name});}}} onPointerUp={e=>{const start=drag.current;drag.current=null;setGhost(null);if(!start||!moved.current)return;const svg=document.querySelector<SVGSVGElement>('svg.plan-svg'),rect=svg?.getBoundingClientRect(),m=svg?.getScreenCTM();if(rect&&m&&e.clientX>=rect.left&&e.clientX<=rect.right&&e.clientY>=rect.top&&e.clientY<=rect.bottom){const point=new DOMPoint(e.clientX,e.clientY).matrixTransform(m.inverse());onPlace(start.key,Math.round(point.x/5)*5,Math.round(point.y/5)*5);}}} onPointerCancel={()=>{drag.current=null;setGhost(null);}} onLostPointerCapture={()=>{drag.current=null;setGhost(null);}} onClick={e=>{if(!moved.current||e.detail===0)onAdd(p.key);}} aria-label={`Añadir ${p.name}`}>{previews[p.key]?<ObjectThumbnail objects={previews[p.key]}/>:<Icon aria-hidden="true"/>}<strong>{p.name}</strong><span>{p.size.join(' × ')} cm</span></Button>;})}</div></section>)}{ghost&&<div className="preset-ghost" style={{left:ghost.x+12,top:ghost.y+12}}>{ghost.name}</div>}</aside>;
}
