'use client';
import {useEffect,useRef,useState} from 'react';
import {PencilRuler,MousePointer2,Undo2,Redo2,Magnet,Plus,Minus,Check} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {newId,validationMessage,type Project,valueCm} from '../domain/model.ts';
import {initialVertices,setRoomOutline,suggestedWallMapping} from '../domain/room-shape.ts';
import {signedArea,type Vertex,type Point} from '../geometry/outline.ts';
import {draftPoint,nextWallIssue,closeDraft,projectOnEdge} from '../geometry/drawing.ts';
export function RoomShapeEditor({project,onChange}:{project:Project;onChange:(p:Project)=>void}){
 const [open,setOpen]=useState(false);return <><Button variant="outline" className="draw-room-trigger" onClick={()=>setOpen(true)}><PencilRuler/> Dibujar</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="builder-dialog"><DialogTitle>Dibujar habitación</DialogTitle><DialogDescription>Clic para cada esquina. Cierra sobre el punto inicial.</DialogDescription>{open&&<ShapeForm project={project} onSave={p=>{onChange(p);setOpen(false);}}/>}</DialogContent></Dialog></>;
}
type Draft={vertices:Vertex[];drawing:boolean};
function ShapeForm({project,onSave}:{project:Project;onSave:(p:Project)=>void}){
 const [draft,setDraft]=useState<Draft>(()=>({vertices:initialVertices(project),drawing:false})),[error,setError]=useState(''),[mapping,setMapping]=useState(()=>suggestedWallMapping(project,draft.vertices));
 const {vertices,drawing}=draft;
 const [past,setPast]=useState<Draft[]>([]),[future,setFuture]=useState<Draft[]>([]),[cursor,setCursor]=useState<Point|null>(null),[snap,setSnap]=useState(true);
 const [extent,setExtent]=useState(Math.min(2000,Math.max(valueCm(project.room.dimensions.width),valueCm(project.room.dimensions.depth),500)+100));
 const svg=useRef<SVGSVGElement>(null),drag=useRef<{id:string;before:Draft}|null>(null);
 const change=(next:Draft)=>{setPast(h=>[...h,draft].slice(-100));setFuture([]);setDraft(next);setError('');};
 const undo=()=>{const previous=past.at(-1);if(previous){setFuture(h=>[...h,draft]);setPast(h=>h.slice(0,-1));setDraft(previous);setError('');}};
 const redo=()=>{const next=future.at(-1);if(next){setPast(h=>[...h,draft]);setFuture(h=>h.slice(0,-1));setDraft(next);setError('');}};
 const [canvasPixels,setCanvasPixels]=useState(600);
 useEffect(()=>{const el=svg.current;if(!el)return;const observer=new ResizeObserver(([entry])=>setCanvasPixels(Math.max(1,Math.min(entry.contentRect.width,entry.contentRect.height))));observer.observe(el);return ()=>observer.disconnect();},[]);
 const point=(e:React.PointerEvent|React.MouseEvent)=>{const m=svg.current?.getScreenCTM();if(!m)return null;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(m.inverse());return draftPoint(p,drawing?vertices.at(-1):undefined,snap,e.shiftKey);};
 function close(){const result=closeDraft(vertices);if(result.error){setError(result.error);return;}change({vertices:result.vertices,drawing:false});setMapping(suggestedWallMapping(project,result.vertices));setCursor(null);}
 function add(p:Point){if(vertices.length>=3&&Math.hypot(p.x-vertices[0].x,p.y-vertices[0].y)<extent/45){close();return;}const issue=nextWallIssue(vertices,p);if(issue){setError(issue);return;}change({vertices:[...vertices,{...p,id:newId()}],drawing:true});}
 function save(){try{const result=closeDraft(vertices);if(result.error)throw new Error(result.error);if(signedArea(vertices)<0&&project.room.fixedElements.length){change({vertices:result.vertices,drawing:false});setMapping(suggestedWallMapping(project,result.vertices));setError('Revisa las paredes asignadas tras ordenar el contorno y pulsa Aplicar.');return;}const v=result.vertices;onSave(setRoomOutline(project,v,Object.fromEntries(project.room.fixedElements.map(o=>[o.id,v.some(p=>p.id===mapping[o.id])?mapping[o.id]:suggestedWallMapping(project,v)[o.id]]))));}catch(e){setError(validationMessage(e));}}
 function finishDrag(){const start=drag.current;if(start){drag.current=null;setPast(h=>[...h,start.before]);setFuture([]);}}
 const last=vertices.at(-1),issue=cursor&&drawing?nextWallIssue(vertices,cursor):'',scale=(extent+80)/canvasPixels;
 return <div className="builder" onKeyDown={e=>{if((e.target as HTMLElement).closest('input,select'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.stopPropagation();if(e.shiftKey)redo();else undo();}if(e.key==='Enter'&&drawing){e.preventDefault();close();}if(e.key==='Backspace'&&drawing){e.preventDefault();undo();}}}>
 <div className="builder-toolbar"><div className="tool-segment"><Button variant={drawing?'default':'ghost'} onClick={()=>{change({vertices:[],drawing:true});setCursor(null);}}><PencilRuler/> Trazar paredes</Button><Button variant={!drawing?'secondary':'ghost'} onClick={()=>{if(drawing)close();}}><MousePointer2/> Editar esquinas</Button></div><div className="tool-segment"><Button variant="ghost" size="icon" aria-label="Deshacer esquina" disabled={!past.length} onClick={undo}><Undo2/></Button><Button variant="ghost" size="icon" aria-label="Rehacer esquina" disabled={!future.length} onClick={redo}><Redo2/></Button></div><Button variant={snap?'secondary':'ghost'} aria-pressed={snap} onClick={()=>setSnap(!snap)}><Magnet/> Ajuste {snap?'5 cm':'libre'}</Button></div>
 <div className="builder-content"><div className="drawing-surface"><div className="drawing-hint">{drawing?(vertices.length?'Siguiente esquina · Shift: recto · Punto inicial: cerrar':'Haz clic para empezar'):'Arrastra una esquina · Clic en una pared para añadir otra'}</div>
 <svg ref={svg} className="builder-canvas" viewBox={`-40 -40 ${extent+80} ${extent+80}`} role="group" aria-label="Lienzo de paredes" tabIndex={0} onPointerDown={e=>{if(e.button!==0||!drawing)return;const p=point(e);if(p)add(p);}} onPointerMove={e=>{const p=point(e);if(!p)return;setCursor(p);if(drag.current)setDraft(d=>({...d,vertices:d.vertices.map(v=>v.id===drag.current!.id?{...v,...p}:v)}));}} onPointerLeave={()=>{if(!drag.current)setCursor(null);}} onPointerUp={finishDrag} onPointerCancel={finishDrag}>
 <defs><pattern id="builder-grid" width={25} height={25} patternUnits="userSpaceOnUse"><path d="M25 0H0V25" fill="none" stroke="#dbe2e9" strokeWidth={scale*.8}/></pattern></defs><rect x={-40} y={-40} width={extent+80} height={extent+80} fill="url(#builder-grid)"/>
 {!drawing&&<polygon points={vertices.map(v=>`${v.x},${v.y}`).join(' ')} fill="#e5f1f4"/>}
 {vertices.map((v,i)=>{const next=vertices[(i+1)%vertices.length];if(drawing&&i===vertices.length-1)return null;return <g key={`wall-${v.id}`}><line x1={v.x} y1={v.y} x2={next.x} y2={next.y} stroke="#263b4e" strokeWidth={7*scale} strokeLinecap="round"/><line className="wall-hit" x1={v.x} y1={v.y} x2={next.x} y2={next.y} stroke="transparent" strokeWidth={24*scale} onPointerDown={e=>{if(drawing)return;e.stopPropagation();const p=point(e);if(p){const projected=projectOnEdge(p,v,next);change({drawing:false,vertices:[...vertices.slice(0,i+1),{...projected,id:newId()},...vertices.slice(i+1)]});}}}/><text x={(v.x+next.x)/2} y={(v.y+next.y)/2-13*scale} className="wall-measure" fontSize={14*scale} textAnchor="middle">{Math.round(Math.hypot(v.x-next.x,v.y-next.y))} cm</text></g>;})}
 {drawing&&last&&cursor&&<g pointerEvents="none"><line x1={last.x} y1={last.y} x2={cursor.x} y2={cursor.y} stroke={issue?'#b42336':'#0b7f85'} strokeWidth={5*scale} strokeDasharray={`${9*scale} ${5*scale}`}/><text x={(last.x+cursor.x)/2} y={(last.y+cursor.y)/2-15*scale} fontSize={15*scale} textAnchor="middle" className="wall-measure">{Math.round(Math.hypot(last.x-cursor.x,last.y-cursor.y))} cm</text><circle cx={cursor.x} cy={cursor.y} r={5*scale} fill="#0b7f85"/></g>}
 {vertices.map((v,i)=><g key={v.id}><circle className="corner-handle" cx={v.x} cy={v.y} r={12*scale} fill={i===0&&drawing?'#0b7f85':'white'} stroke="#0b7f85" strokeWidth={2*scale} tabIndex={0} role="button" aria-label={`Esquina ${i+1}: X ${v.x}, Y ${v.y}`} onPointerDown={e=>{e.stopPropagation();if(drawing){if(i===0&&vertices.length>=3)close();return;}drag.current={id:v.id,before:draft};e.currentTarget.setPointerCapture(e.pointerId);}} onKeyDown={e=>{if(drawing&&i===0&&e.key==='Enter'){e.preventDefault();e.stopPropagation();close();return;}const d={ArrowLeft:[-5,0],ArrowRight:[5,0],ArrowUp:[0,-5],ArrowDown:[0,5]}[e.key];if(d){e.preventDefault();change({...draft,vertices:vertices.map(p=>p.id===v.id?{...p,...draftPoint({x:p.x+d[0],y:p.y+d[1]},undefined,false,false)}:p)});}if(e.key==='Delete'){e.preventDefault();change({...draft,vertices:vertices.filter(p=>p.id!==v.id)});}}}/></g>)}
 <text x={0} y={-18*scale} fontSize={12*scale} fill="#46566b">0,0</text></svg>
 <div className="drawing-zoom"><Button size="icon" variant="outline" aria-label="Acercar dibujo" onClick={()=>setExtent(v=>Math.max(100,v/1.25))}><Plus/></Button><Button size="icon" variant="outline" aria-label="Alejar dibujo" onClick={()=>setExtent(v=>Math.min(2000,v*1.25))}><Minus/></Button></div></div>
 <aside className="drawing-settings"><h3>{drawing?'Nuevo contorno':'Tu habitación'}</h3><p>{vertices.length} esquinas{!drawing?` · ${(Math.abs(signedArea(vertices))/10000).toFixed(2)} m²`:''}</p>{drawing&&<Button onClick={close} disabled={vertices.length<3}><Check/> Cerrar contorno</Button>}
 <details><summary>Coordenadas exactas</summary><Button variant="outline" size="sm" disabled={vertices.length>=32} onClick={()=>change({...draft,vertices:[...vertices,{id:newId(),x:0,y:0}]})}>Añadir esquina</Button><div className="vertex-rows">{vertices.map((v,i)=><div key={v.id}><span>{i+1}</span>{(['x','y'] as const).map(axis=><label key={axis}>{axis.toUpperCase()}<Input aria-label={`Esquina ${i+1} ${axis.toUpperCase()}`} type="number" min={0} max={2000} value={v[axis]} onChange={e=>change({...draft,vertices:vertices.map(p=>p.id===v.id?{...p,[axis]:Number(e.target.value)}:p)})}/></label>)}</div>)}</div></details>
 {!drawing&&project.room.fixedElements.length>0&&<details open><summary>Puertas y ventanas</summary>{project.room.fixedElements.map(o=><label key={o.id}>{o.name}<NativeSelect aria-label={`Pared para ${o.name}`} value={vertices.some(v=>v.id===mapping[o.id])?mapping[o.id]:suggestedWallMapping(project,vertices)[o.id]} onChange={e=>setMapping(m=>({...m,[o.id]:e.target.value}))}>{vertices.map((v,i)=><NativeSelectOption key={v.id} value={v.id}>Pared {i+1}</NativeSelectOption>)}</NativeSelect></label>)}<p>Revisa la pared asignada. Se conservan las medidas de cada hueco.</p></details>}
 <details><summary>Atajos</summary><p>Enter: cerrar. Retroceso o Ctrl+Z: deshacer. Shift: pared recta. Flechas: mover esquina. Suprimir: quitar esquina. Esc: salir sin aplicar.</p></details></aside></div>
 <footer className="builder-footer"><span role="status">{error|| (drawing?'El trazado se guardará cuando cierres el contorno.':'Los cambios se aplican juntos y se pueden deshacer.')}</span><Button disabled={drawing||vertices.length<3} onClick={save}>Aplicar habitación</Button></footer></div>;
}
