using Autodesk.Revit.Attributes;
using Autodesk.Revit.DB;
using Autodesk.Revit.DB.Structure;
using Autodesk.Revit.DB.ExtensibleStorage;
using Autodesk.Revit.UI;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Security.Cryptography;
using Forms=System.Windows.Forms;
namespace Habitacion.Revit;
[Transaction(TransactionMode.Manual)]
public class ImportProject:IExternalCommand {
 internal static readonly Guid SnapshotSchema=new("7e9d429a-42e7-42a9-ae17-b5a43345b806");
 public Result Execute(ExternalCommandData data,ref string message,ElementSet elements){
  var doc=data.Application.ActiveUIDocument?.Document;if(doc==null||doc.IsFamilyDocument){message="Abre un proyecto Revit (.rvt).";return Result.Failed;}
  using var pick=new Forms.OpenFileDialog{Filter="Proyecto habitación (*.habitacion.json)|*.habitacion.json|JSON (*.json)|*.json"};if(pick.ShowDialog()!=Forms.DialogResult.OK)return Result.Cancelled;
  JsonNode p;try{if(new FileInfo(pick.FileName).Length>40_000_000)throw new Exception("Archivo mayor de 40 MB.");var root=JsonNode.Parse(File.ReadAllText(pick.FileName))!;p=(root["project"]??root).DeepClone();if(!(p["schemaVersion"]?.GetValue<int>() is 6 or 7 or 8 or 9 or 10 or 11)||Bridge.Text(p,"unit")!="cm")throw new Exception("Exporta un proyecto V6–V11 desde la web.");if(Bridge.Text(p["room"]!,"shape")=="polygon")throw new Exception("Este complemento todavía no importa contornos poligonales. La web conserva el contorno; no se sustituirá por un rectángulo.");}catch(Exception e){message=e.Message;return Result.Failed;}
  if(TaskDialog.Show("Importar habitación","Se añadirán nuevos elementos al documento activo. La importación no actualiza instancias anteriores. Se informará de familias o parámetros no compatibles.",TaskDialogCommonButtons.Ok|TaskDialogCommonButtons.Cancel)!=TaskDialogResult.Ok)return Result.Cancelled;
  var report=new List<string>();var walls=new Dictionary<string,Wall>();var mapping=new Dictionary<string,string>();var room=p["room"]!;double width=Bridge.Measure(room["dimensions"]!["width"]!),depth=Bridge.Measure(room["dimensions"]!["depth"]!),height=Bridge.Measure(room["dimensions"]!["height"]!);Level? level=null;string token=Guid.NewGuid().ToString("N")[..8];
  try{Bridge.Transaction(doc,"Habitación: estructura",()=>{
   level=Level.Create(doc,0);level.Name="Habitación "+token;var top=Level.Create(doc,Bridge.Ft(height));top.Name="Techo "+token;
   var original=new FilteredElementCollector(doc).OfClass(typeof(WallType)).Cast<WallType>().First(w=>w.Kind==WallKind.Basic);var wt=(WallType)original.Duplicate("Habitación "+token);var compound=wt.GetCompoundStructure();if(compound==null)throw new Exception("El tipo de muro no admite capas.");double desired=Bridge.Ft(Bridge.N(room,"wallThicknessCm")),total=compound.GetWidth();for(int i=0;i<compound.LayerCount;i++)if(compound.GetLayerWidth(i)>0)compound.SetLayerWidth(i,compound.GetLayerWidth(i)/total*desired);wt.SetCompoundStructure(compound);double t=Bridge.Cm(wt.Width)/2;
   void Wall(string key,double ax,double ay,double bx,double by)=>walls[key]=Autodesk.Revit.DB.Wall.Create(doc,Line.CreateBound(Bridge.Point(ax,ay,0),Bridge.Point(bx,by,0)),wt.Id,level.Id,Bridge.Ft(height),0,false,false);
   Wall("north",-t,-t,width+t,-t);Wall("south",-t,depth+t,width+t,depth+t);Wall("west",-t,-t,-t,depth+t);Wall("east",width+t,-t,width+t,depth+t);
   var loop=new CurveLoop();var corners=new[]{Bridge.Point(0,0,0),Bridge.Point(width,0,0),Bridge.Point(width,depth,0),Bridge.Point(0,depth,0)};for(int i=0;i<4;i++)loop.Append(Line.CreateBound(corners[i],corners[(i+1)%4]));
   var ft=new FilteredElementCollector(doc).OfClass(typeof(FloorType)).Cast<FloorType>().First();Floor.Create(doc,new List<CurveLoop>{loop},ft.Id,level.Id);
   var ct=new FilteredElementCollector(doc).OfClass(typeof(CeilingType)).Cast<CeilingType>().First();var ceiling=Ceiling.Create(doc,new List<CurveLoop>{loop},ct.Id,top.Id);ceiling.get_Parameter(BuiltInParameter.CEILING_HEIGHTABOVELEVEL_PARAM)?.Set(0.0);
  });}catch(Exception e){message="No se creó la estructura: "+e.Message;return Result.Failed;}
  var cache=new Dictionary<string,Family>();string folder=Path.GetDirectoryName(pick.FileName)!;string temp=Path.Combine(Path.GetTempPath(),"Habitacion-"+token);Directory.CreateDirectory(temp);
  foreach(var opening in (JsonArray)room["fixedElements"]!)if(opening?["swing"]!=null)report.Add(Bridge.Text(opening!,"name")+": apertura de hoja conservada en JSON; bisagra/sentido/ángulo no aplicados a parámetros de familia todavía.");
  if(room["fixedVolumes"] is JsonArray fixedVolumes)foreach(var volume in fixedVolumes)report.Add(Bridge.Text(volume!,"name")+": volumen fijo conservado en JSON; sin familia ni geometría Revit generada.");
  if(p["assets"] is JsonArray assets&&assets.Count>0)report.Add("Los archivos asociados externos no se importan; usa la copia .habitacion.pack en la web. Los originales RFA embebidos sí se procesan.");
  var entries=((JsonArray)p["objects"]!).Select(o=>(node:o!,opening:false)).Concat(((JsonArray)room["fixedElements"]!).Select(o=>(node:o!,opening:true)));
  foreach(var item in entries){var o=item.node;if(o["model"]?["kind"]?.GetValue<string>()=="compound")report.Add(Bridge.Text(o,"name")+": piezas procedurales conservadas en snapshot; no alteran la geometría de la familia Revit.");string id=Bridge.Text(o,"id"),name=Bridge.Text(o,"name");try{
   Bridge.Transaction(doc,"Habitación: "+name,()=>{
    var binding=o["revit"];if(binding==null){if(item.opening){string wall=Bridge.Text(o,"wallId");double start=Bridge.Measure(o["offset"]!),sill=Bridge.Measure(o["sill"]!),w=Bridge.Measure(o["width"]!),h=Bridge.Measure(o["height"]!);bool horizontal=wall=="north"||wall=="south";double fixedAxis=wall=="north"?0:wall=="south"?depth:wall=="west"?0:width;var a=horizontal?Bridge.Point(start,fixedAxis,sill):Bridge.Point(fixedAxis,start,sill);var b=horizontal?Bridge.Point(start+w,fixedAxis,sill+h):Bridge.Point(fixedAxis,start+w,sill+h);doc.Create.NewOpening(walls[wall],a,b);report.Add(name+": hueco sin familia.");return;}throw new Exception("Objeto sin familia Revit; no se creó geometría falsa.");}
    var familyData=((JsonArray)p["families"]!).FirstOrDefault(f=>Bridge.Text(f!,"id")==Bridge.Text(binding,"familyId"))??throw new Exception("Familia ausente del catálogo.");
    string fid=Bridge.Text(familyData,"id"),placement=Bridge.Text(familyData,"placement");if(placement=="unsupported")throw new Exception("Hospedaje no compatible aún (cara, techo, adaptativa u otro).");
    if(!cache.TryGetValue(fid,out var family)||!family.IsValidObject){string fileName=Path.GetFileName(Bridge.Text(familyData,"fileName"));if(!fileName.EndsWith(".rfa",StringComparison.OrdinalIgnoreCase))throw new Exception("Ruta de familia inválida.");string path=Path.Combine(folder,fileName);string raw=Bridge.Text(familyData,"originalBase64");if(!string.IsNullOrEmpty(raw)){var bytes=Convert.FromBase64String(raw);if(bytes.Length>8_000_000)throw new Exception("RFA demasiado grande.");if(fid.Length==64&&!string.Equals(Convert.ToHexString(SHA256.HashData(bytes)),fid,StringComparison.OrdinalIgnoreCase))throw new Exception("El original no coincide con el identificador SHA256.");path=Path.Combine(temp,Convert.ToHexString(SHA256.HashData(bytes))+".rfa");File.WriteAllBytes(path,bytes);}if(!File.Exists(path))throw new Exception("Falta .rfa: "+fileName);if(!doc.LoadFamily(path,out family)||family==null){family=new FilteredElementCollector(doc).OfClass(typeof(Family)).Cast<Family>().FirstOrDefault(f=>f.Name==Bridge.Text(familyData,"name"));if(family==null)throw new Exception("No se pudo cargar la familia.");}cache[fid]=family;}
    var typeData=((JsonArray)familyData["types"]!).First(t=>Bridge.Text(t!,"id")==Bridge.Text(binding,"typeId"))!;var original=family.GetFamilySymbolIds().Select(e=>(FamilySymbol)doc.GetElement(e)).FirstOrDefault(s=>s.Name==Bridge.Text(typeData,"name"))??throw new Exception("Tipo no encontrado.");
    var symbol=(FamilySymbol)original.Duplicate("Habitacion_"+token+"_"+id);symbol.Activate();doc.Regenerate();
    JsonNode dims=item.opening?new JsonObject{["width"]=Bridge.Measure(o["width"]!),["depth"]=1,["height"]=Bridge.Measure(o["height"]!)}:new JsonObject{["width"]=Bridge.Measure(o["dimensions"]!["width"]!),["depth"]=Bridge.Measure(o["dimensions"]!["depth"]!),["height"]=Bridge.Measure(o["dimensions"]!["height"]!)};
    var values=(JsonObject)binding["parameters"]!.DeepClone();foreach(string axis in new[]{"width","depth","height"}){if(item.opening&&axis=="depth")continue;string key=Bridge.Text(typeData["dimensionParameters"]!,axis);if(!string.IsNullOrEmpty(key))values[key]=dims[axis]!.DeepClone();}
    var definitions=(JsonArray)typeData["parameters"]!;
    void Parameters(Element target,string scope){foreach(var pair in values){var definition=definitions.FirstOrDefault(q=>Bridge.Text(q!,"key")==pair.Key);if(definition==null){report.Add(name+": parámetro desconocido "+pair.Key);continue;}if(Bridge.Text(definition,"scope")!=scope)continue;try{Bridge.SetParameter(target,definition,pair.Value!);}catch(Exception e){report.Add(name+": "+e.Message);}}}
    Parameters(symbol,"type");doc.Regenerate();FamilyInstance instance;
    if(item.opening){if(placement!="wall")throw new Exception("Puerta/ventana requiere hospedaje de muro compatible.");string wall=Bridge.Text(o,"wallId");double center=Bridge.Measure(o["offset"]!)+Bridge.N(dims,"width")/2,z=Bridge.Measure(o["sill"]!);bool horizontal=wall=="north"||wall=="south";var position=horizontal?Bridge.Point(center,wall=="north"?0:depth,z):Bridge.Point(wall=="west"?0:width,center,z);instance=doc.Create.NewFamilyInstance(position,symbol,walls[wall],level!,StructuralType.NonStructural);Parameters(instance,"instance");doc.Regenerate();var box=instance.get_BoundingBox(null)??throw new Exception("Sin envolvente.");double actualWidth=Bridge.Cm(horizontal?box.Max.X-box.Min.X:box.Max.Y-box.Min.Y);if(Math.Abs(actualWidth-Bridge.N(dims,"width"))>.5||Math.Abs(Bridge.Cm(box.Max.Z-box.Min.Z)-Bridge.N(dims,"height"))>.5)throw new Exception("Dimensiones de hueco incompatibles; revisa mapeo de parámetros. No se escaló la familia.");}
    else{if(placement!="free")throw new Exception("Este objeto necesita un anfitrión; no se coloca como mueble libre.");instance=doc.Create.NewFamilyInstance(XYZ.Zero,symbol,level!,StructuralType.NonStructural);Parameters(instance,"instance");doc.Regenerate();var box=instance.get_BoundingBox(null)??throw new Exception("Sin envolvente.");var actual=Bridge.Dimensions(box);foreach(string axis in new[]{"width","depth","height"})if(Math.Abs(Bridge.N(actual,axis)-Bridge.N(dims,axis))>.5)throw new Exception("Medida real no reproducible: "+axis+". Se omite, sin escalar ni cambiar medidas.");var pos=o["position"]!;var target=Bridge.Point(Bridge.N(pos,"x"),Bridge.N(pos,"y"),Bridge.N(pos,"z"));ElementTransformUtils.MoveElement(doc,instance.Id,target-new XYZ((box.Min.X+box.Max.X)/2,(box.Min.Y+box.Max.Y)/2,box.Min.Z));double angle=-Bridge.N(o,"rotationDeg")*Math.PI/180;if(Math.Abs(angle)>1e-8)ElementTransformUtils.RotateElement(doc,instance.Id,Line.CreateBound(target,target+XYZ.BasisZ),angle);}
    if(o["hidden"]?.GetValue<bool>()==true&&instance.CanBeHidden(doc.ActiveView))doc.ActiveView.HideElements(new List<ElementId>{instance.Id});mapping[id]=instance.UniqueId;
   });
  }catch(Exception e){report.Add(name+": "+e.Message);mapping.Remove(id);}}
  foreach(JsonNode? g in (JsonArray)p["groups"]!){try{var ids=((JsonArray)p["objects"]!).Where(o=>Bridge.Text(o!,"groupId")==Bridge.Text(g!,"id")&&mapping.ContainsKey(Bridge.Text(o!,"id"))).Select(o=>doc.GetElement(mapping[Bridge.Text(o!,"id")]).Id).ToList();if(ids.Count<2){report.Add(Bridge.Text(g!,"name")+": grupo incompleto, conservado en JSON.");continue;}Bridge.Transaction(doc,"Habitación: grupo",()=>doc.Create.NewGroup(ids));}catch(Exception e){report.Add("Grupo: "+e.Message);}}
  try{Bridge.Transaction(doc,"Guardar intercambio",()=>{var schema=Schema.Lookup(SnapshotSchema);if(schema==null){var builder=new SchemaBuilder(SnapshotSchema);builder.SetSchemaName("HabitacionSnapshot");builder.AddSimpleField("Json",typeof(string));schema=builder.Finish();}var store=DataStorage.Create(doc);store.Name="Habitacion_"+token;var entity=new Entity(schema);entity.Set(schema.GetField("Json"),p.ToJsonString());store.SetEntity(entity);});}catch(Exception e){report.Add("No se guardó snapshot: "+e.Message);}
  report.Insert(0,$"Instancias importadas: {mapping.Count}. Los muebles fuera de límites no se bloquean. Visibilidad aplicada solo a la vista activa. Informe no confirma equivalencia BIM completa.");
  File.WriteAllLines(pick.FileName+".revit-report.txt",report);try{Directory.Delete(temp,true);}catch{}TaskDialog.Show("Habitación",$"Importadas {mapping.Count} instancias. Consulta {pick.FileName}.revit-report.txt");return Result.Succeeded;
 }
}
[Transaction(TransactionMode.ReadOnly)]
public class ExportSnapshot:IExternalCommand {
 public Result Execute(ExternalCommandData data,ref string message,ElementSet elements){var doc=data.Application.ActiveUIDocument?.Document;var schema=Schema.Lookup(ImportProject.SnapshotSchema);if(doc==null||schema==null){message="No hay un proyecto importado.";return Result.Failed;}var snapshots=new FilteredElementCollector(doc).OfClass(typeof(DataStorage)).Cast<DataStorage>().Where(s=>s.GetEntity(schema).IsValid()).ToList();if(snapshots.Count!=1){message="Se requiere exactamente un snapshot importado en este documento; evita exportar una habitación ambigua.";return Result.Failed;}using var save=new Forms.SaveFileDialog{Filter="Proyecto (*.habitacion.json)|*.habitacion.json",FileName="snapshot.habitacion.json"};if(save.ShowDialog()!=Forms.DialogResult.OK)return Result.Cancelled;File.WriteAllText(save.FileName,snapshots[0].GetEntity(schema).Get<string>(schema.GetField("Json")));TaskDialog.Show("Exportación","Se exportó el snapshot original. Los cambios posteriores hechos en Revit NO se incorporan todavía.");return Result.Succeeded;}
}
