import {roomWalls,roomOutline,atWall} from '../geometry/outline.ts';
import {objectSolids,solidFootprint} from '../geometry/object-parts.ts';
import {doorLeaf,doorAngleAtPoint,maxDoorAngle} from '../geometry/door-leaf.ts';
import {useRef,useState,useEffect} from 'react';
import {footprint,type MovableObject} from '../domain/objects.ts';
import { roomGeometry } from '../geometry/room.ts';
import { openingBounds,wallLabels } from '../domain/openings.ts';
import type { Room } from '../domain/model.ts';
export function Plan2D({room,onMoveFixed,onDoorAngle,onSelectFixed,selectedOpening,onSelectOpening,onMoveOpening,selectedIds=[],onGestureStart,onGestureEnd,objects=[],warnings=new Map(),selected,onSelect,onMove,onDropPreset}:{onMoveFixed?:(id:string,x:number,y:number)=>void;onDropPreset?:(key:string,x:number,y:number)=>void;room:Room;onDoorAngle?:(id:string,angle:number)=>void;onSelectFixed?:(id:string)=>void;selectedOpening?:string|null;onSelectOpening?:(id:string)=>void;onMoveOpening?:(id:string,offset:number)=>boolean;selectedIds?:string[];onGestureStart?:()=>void;onGestureEnd?:()=>void;objects?:MovableObject[];warnings?:Map<string,string[]>;selected?:string|null;onSelect?:(id:string,multi?:boolean)=>void;onMove?:(id:string,x:number,y:number)=>boolean}) {
  const fixedDrag=useRef<{id:string;x:number;y:number;start:{x:number;y:number}}|null>(null),fixedMoved=useRef(false);
  const doorDrag=useRef<string|null>(null);
  const openingDrag=useRef<{id:string;tangent:{x:number;y:number};clientX:number;clientY:number;offset:number}|null>(null);
  const drag=useRef<{id:string;clientX:number;clientY:number;x:number;y:number}|null>(null),svg=useRef<SVGSVGElement>(null);
  const [viewport,setViewport]=useState({width:500,height:500});
  useEffect(()=>{const element=svg.current;if(!element)return;const observer=new ResizeObserver(()=>{const r=element.getBoundingClientRect();if(r.width&&r.height)setViewport({width:r.width,height:r.height});});observer.observe(element);return ()=>observer.disconnect();},[]);
  const [lockedView,setLockedView]=useState<{minX:number;minY:number;maxX:number;maxY:number}|null>(null);
  const [invalid,setInvalid]=useState<{x:number;y:number}|null>(null);
  function point(e:React.PointerEvent){const matrix=svg.current?.getScreenCTM();return matrix?new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse()):null;}

  const g=roomGeometry(room),walls=roomWalls(room),outline=roomOutline(room).map(p=>`${p.x},${p.y}`).join(' ');
  const visible=objects.filter(o=>!o.hidden),selectedGroup=objects.find(o=>o.id===selected)?.groupId;
  const leaves=room.fixedElements.flatMap(o=>{const leaf=doorLeaf(o,g.width,g.depth,room);return leaf?[leaf]:[];});
  const points=[...visible.flatMap(footprint),...room.fixedVolumes.flatMap(footprint),...leaves.flatMap(l=>[...l.arcPoints,l.hinge])],autoMinX=Math.min(0,...points.map(p=>p.x)),autoMinY=Math.min(0,...points.map(p=>p.y)),autoMaxX=Math.max(g.width,...points.map(p=>p.x)),autoMaxY=Math.max(g.depth,...points.map(p=>p.y));
  const {minX,minY,maxX,maxY}=lockedView??{minX:autoMinX,minY:autoMinY,maxX:autoMaxX,maxY:autoMaxY};
  const scale=Math.max(maxX-minX,maxY-minY)/450;
  const margin=65*scale;
  const unit=Math.max((maxX-minX+2*margin)/viewport.width,(maxY-minY+2*margin)/viewport.height);
  const font=14*unit;
  return <svg onDragOver={e=>{if(e.dataTransfer.types.includes('application/x-room-preset'))e.preventDefault();}} onDrop={e=>{e.preventDefault();const m=svg.current?.getScreenCTM();if(m){const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(m.inverse());onDropPreset?.(e.dataTransfer.getData('application/x-room-preset'),Math.round(p.x/5)*5,Math.round(p.y/5)*5);}}} ref={svg} style={{touchAction:'none'}} onPointerMove={e=>{if(fixedDrag.current){const p=point(e),d=fixedDrag.current;if(p){fixedMoved.current=true;onMoveFixed?.(d.id,Math.round((d.x+p.x-d.start.x)/5)*5,Math.round((d.y+p.y-d.start.y)/5)*5);}return;}if(doorDrag.current){const o=room.fixedElements.find(o=>o.id===doorDrag.current),p=point(e);if(o&&p)onDoorAngle?.(o.id,doorAngleAtPoint(o,g.width,g.depth,p,room));return;}if(openingDrag.current){const d=openingDrag.current,m=svg.current?.getScreenCTM();if(!m)return;const a=new DOMPoint(d.clientX,d.clientY).matrixTransform(m.inverse()),b=point(e);if(!b)return;const offset=Math.round((d.offset+((b.x-a.x)*d.tangent.x+(b.y-a.y)*d.tangent.y))/5)*5;setInvalid(onMoveOpening?.(d.id,offset)?null:b);return;}if(!drag.current)return;const p=point(e);if(!p)return;const matrix=svg.current?.getScreenCTM();if(!matrix)return;const start=new DOMPoint(drag.current.clientX,drag.current.clientY).matrixTransform(matrix.inverse());const x=Math.round((drag.current.x+p.x-start.x)/5)*5,y=Math.round((drag.current.y+p.y-start.y)/5)*5;setInvalid(onMove?.(drag.current.id,x,y)?null:{x,y});}} onPointerUp={()=>{if(drag.current||openingDrag.current||doorDrag.current||fixedDrag.current)onGestureEnd?.();fixedDrag.current=null;drag.current=null;openingDrag.current=null;doorDrag.current=null;setLockedView(null);}} onPointerCancel={()=>{if(drag.current||openingDrag.current||doorDrag.current||fixedDrag.current)onGestureEnd?.();fixedDrag.current=null;drag.current=null;openingDrag.current=null;doorDrag.current=null;setLockedView(null);setInvalid(null);}} onLostPointerCapture={()=>{if(drag.current||openingDrag.current||doorDrag.current||fixedDrag.current)onGestureEnd?.();fixedDrag.current=null;drag.current=null;openingDrag.current=null;doorDrag.current=null;setLockedView(null);}} className="plan-svg" viewBox={`${minX-margin} ${minY-margin} ${maxX-minX+2*margin} ${maxY-minY+2*margin}`} role="group" aria-label={`Plano de ${g.width} por ${g.depth} centímetros`}>
    <defs><pattern id="room-grid" width="25" height="25" patternUnits="userSpaceOnUse"><path d="M 25 0 L 0 0 0 25" fill="none" stroke="#cad8e8" strokeWidth={.65*scale}/></pattern></defs>
    <polygon points={outline} fill="#f0f6fe"/>
    <polygon points={outline} fill="url(#room-grid)"/>
    {g.planWalls.map(w=><rect key={w.id} x={w.center.x-w.size.x/2} y={w.center.y-w.size.y/2} width={w.size.x} height={w.size.y} transform={`rotate(${w.rotationDeg??0} ${w.center.x} ${w.center.y})`} fill="#344861"/>)}
    {room.fixedElements.map(o=>{
      const b=openingBounds(o),wall=walls.find(w=>w.id===o.wallId)!,t=room.wallThicknessCm,center=atWall(wall,b.start+b.width/2,-t/2),angle=Math.atan2(wall.tangent.y,wall.tangent.x)*180/Math.PI;
      const leaf=doorLeaf(o,g.width,g.depth,room),color=o.kind==='window'?'#156084':'#79511e';
      return <g key={o.id} role="button" tabIndex={0} aria-pressed={selectedOpening===o.id} style={{cursor:'grab'}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelectOpening?.(o.id);}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();onSelectOpening?.(o.id);onMoveOpening?.(o.id,b.start+(['ArrowLeft','ArrowUp'].includes(e.key)?-5:5));}}} onPointerDown={e=>{e.preventDefault();e.stopPropagation();onSelectOpening?.(o.id);onGestureStart?.();setLockedView({minX,minY,maxX,maxY});openingDrag.current={id:o.id,tangent:wall.tangent,clientX:e.clientX,clientY:e.clientY,offset:b.start};e.currentTarget.setPointerCapture(e.pointerId);}} aria-label={`Mover ${o.name}, ${wall.label}, a ${b.start} cm del inicio`}>
        {leaf&&<g data-door-leaf={o.id}>
          <polyline points={leaf.arcPoints.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke={color} strokeWidth={scale} strokeDasharray={`${4*scale} ${3*scale}`} pointerEvents="none"/>
          <line x1={leaf.hinge.x} y1={leaf.hinge.y} x2={leaf.end.x} y2={leaf.end.y} stroke={color} strokeWidth={o.swing!.thicknessCm}/>
        </g>}
        <rect x={center.x-b.width/2} y={center.y-t/2} width={b.width} height={t} transform={`rotate(${angle} ${center.x} ${center.y})`} fill={o.kind==='window'?'#d7f0fc':'#fff2dd'} stroke={selectedOpening===o.id?'#073aad':color} strokeWidth={(selectedOpening===o.id?3:1)*scale}/>
        <title>{o.name}: {b.width} × {b.height} cm</title>
      </g>;
    })}
    {walls.map(w=>{const p=atWall(w,w.length/2,18*scale);return <text key={w.id} x={p.x} y={p.y} textAnchor="middle" fontSize={14*unit} fill="#344861">{room.shape==='polygon'?w.label.replace('Pared ','P'):w.label.split(' ·')[0]}</text>;})}
    <g stroke="#657d99" strokeWidth={scale} fill="none">
      <path d={`M 0 ${-35*scale} H ${g.width} M 0 ${-42*scale} V ${-28*scale} M ${g.width} ${-42*scale} V ${-28*scale}`}/>
      <path d={`M ${-35*scale} 0 V ${g.depth} M ${-42*scale} 0 H ${-28*scale} M ${-42*scale} ${g.depth} H ${-28*scale}`}/>
    </g>
    <g fill="#344861" fontSize={font} fontFamily="system-ui" textAnchor="middle">
      <text x={g.width/2} y={-44*scale}>X → 0 a {g.width} cm</text>
      <text transform={`translate(${-44*scale},${g.depth/2}) rotate(-90)`}>Y ↓ 0 a {g.depth} cm</text>
      <text visibility={room.shape==='polygon'||objects.length||room.fixedVolumes.length?"hidden":"visible"} x={g.width/2} y={g.depth/2-8*scale} fontSize={25*scale} fontWeight="600">{g.areaM2.toLocaleString('es-ES',{maximumFractionDigits:2})} m²</text>
      <text visibility={room.shape==='polygon'||objects.length||room.fixedVolumes.length?"hidden":"visible"} x={g.width/2} y={g.depth/2+17*scale} fill="#60758e">Interior de la habitación</text>
      <text x={g.width/2} y={g.depth+42*scale} fill="#60758e">Z ↑ suelo 0 · techo {g.height} cm</text>
    </g>
    {room.fixedVolumes.map(v=><g key={v.id} role="button" tabIndex={0} aria-label={`Editar elemento fijo ${v.name}`} onPointerDown={e=>{const p=point(e);if(!p)return;e.preventDefault();fixedMoved.current=false;fixedDrag.current={id:v.id,x:v.position.x,y:v.position.y,start:p};onGestureStart?.();setLockedView({minX,minY,maxX,maxY});e.currentTarget.setPointerCapture(e.pointerId);}} onClick={()=>{if(!fixedMoved.current)onSelectFixed?.(v.id);}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelectFixed?.(v.id);}const delta={ArrowLeft:[-5,0],ArrowRight:[5,0],ArrowUp:[0,-5],ArrowDown:[0,5]}[e.key];if(delta){e.preventDefault();onMoveFixed?.(v.id,v.position.x+delta[0],v.position.y+delta[1]);}}} style={{cursor:'pointer'}}><title>{v.name} · elemento fijo</title><polygon points={footprint(v).map(p=>`${p.x},${p.y}`).join(' ')} fill={warnings.has(v.id)?'#dc2626':v.color} stroke="#334155" strokeWidth={2*scale} strokeDasharray={`${4*scale} ${2*scale}`}/><text x={v.position.x} y={v.position.y} textAnchor="middle" fill="#172b46" stroke="white" strokeWidth={3*unit} paintOrder="stroke" fontSize={14*unit} pointerEvents="none">{v.name}</text></g>)}
    {visible.map(o=><g key={o.id} role="button" tabIndex={0} aria-label={`Seleccionar ${o.name}, X ${o.position.x}, Y ${o.position.y}, Z ${o.position.z}, giro ${o.rotationDeg}`} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect?.(o.id,e.ctrlKey||e.metaKey);}const delta={ArrowLeft:[-5,0],ArrowRight:[5,0],ArrowUp:[0,-5],ArrowDown:[0,5]}[e.key];if(delta){e.preventDefault();onSelect?.(o.id);onMove?.(o.id,o.position.x+delta[0],o.position.y+delta[1]);}}} onPointerDown={e=>{e.preventDefault();const p=point(e);if(!p)return;if(!selectedIds.includes(o.id)||e.ctrlKey||e.metaKey)onSelect?.(o.id,e.ctrlKey||e.metaKey);if(e.ctrlKey||e.metaKey)return;onGestureStart?.();setLockedView({minX,minY,maxX,maxY});setInvalid(null);drag.current={id:o.id,clientX:e.clientX,clientY:e.clientY,x:o.position.x,y:o.position.y};e.currentTarget.setPointerCapture(e.pointerId);}} style={{cursor:'grab'}}>
      {objectSolids(o).sort((a,b)=>a.position.z-b.position.z).map(solid=><polygon key={solid.partId} points={solidFootprint(solid,false).map(p=>`${p.x},${p.y}`).join(' ')} fill={warnings.has(o.id)?'#dc2626':o.material.color} fillOpacity={.85} stroke={warnings.has(o.id)?'#991b1b':(selectedIds.includes(o.id)||selected===o.id||(selectedGroup&&selectedGroup===o.groupId))?'#073aad':'#263f56'} strokeWidth={((selectedIds.includes(o.id)||selected===o.id||(selectedGroup&&selectedGroup===o.groupId))?3:1)*scale}/>)}<text x={o.position.x} y={o.position.y} textAnchor="middle" fontSize={16*unit} fill="#172b46" stroke="white" strokeWidth={3*unit} paintOrder="stroke" fontWeight="600" pointerEvents="none">{o.name}</text>
    </g>)}
    {leaves.map(leaf=><circle key={`handle-${leaf.id}`} cx={leaf.end.x} cy={leaf.end.y} r={12*unit} fill="#fff" stroke="#976b29" strokeWidth={2*scale} style={{cursor:'grab'}} role="slider" tabIndex={0} aria-label={`Abrir/cerrar ${leaf.name}`} aria-valuemin={0} aria-valuemax={maxDoorAngle(room.fixedElements.find(o=>o.id===leaf.id)!,room)} aria-valuenow={room.fixedElements.find(o=>o.id===leaf.id)?.swing?.angleDeg} onPointerDown={e=>{e.preventDefault();e.stopPropagation();doorDrag.current=leaf.id;setLockedView({minX,minY,maxX,maxY});onGestureStart?.();e.currentTarget.setPointerCapture(e.pointerId);}} onKeyDown={e=>{const a=room.fixedElements.find(o=>o.id===leaf.id)?.swing?.angleDeg??0;const next={ArrowLeft:Math.max(0,a-5),ArrowRight:Math.min(180,a+5),Home:0,End:180}[e.key];if(next!==undefined){e.preventDefault();onDoorAngle?.(leaf.id,next);}}}><title>Arrastra para abrir o cerrar · solo referencia</title></circle>)}
    {invalid&&<g pointerEvents="none" stroke="#b91c1c" strokeWidth={3*scale}><circle cx={invalid.x} cy={invalid.y} r={12*scale} fill="#fee2e2"/><path d={`M ${invalid.x-7*scale} ${invalid.y-7*scale} l ${14*scale} ${14*scale} m 0 ${-14*scale} l ${-14*scale} ${14*scale}`}/></g>}
    <text x={8*scale} y={16*scale} fill="#073aad" fontSize={12*scale}>0,0,0</text>
    <circle cx="0" cy="0" r={3*scale} fill="#2366dc"/>
  </svg>;
}
