import {roomWalls} from '../geometry/outline.ts';
/* eslint-disable @next/next/no-img-element -- thumbnails are bounded, local PNG data from the Revit manifest */
'use client';
import {useRef,useState,useEffect} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {type Project,validationMessage} from '../domain/model.ts';
import {WALL_IDS,wallLabels,type WallId} from '../domain/openings.ts';
import {CATEGORIES,type RevitFamily,type RevitBinding} from './schema.ts';
import {addPending,importManifest,addFamily,suggestions,exportRevit,type Placement} from './operations.ts';
import {readRfa,downloadData,downloadRfa} from './files';
import {Parameters} from './Parameters';
export function FamiliesPanel({project,onChange,onAdded}:{project:Project;onChange:(p:Project)=>void;onAdded:(id:string,structural:boolean)=>void}){
 const [open,setOpen]=useState(false),[search,setSearch]=useState(''),[category,setCategory]=useState(''),[selected,setSelected]=useState<string|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[brief,setBrief]=useState(''),[asked,setAsked]=useState(false);
 const file=useRef<HTMLInputElement>(null),manifest=useRef<HTMLInputElement>(null),latest=useRef(project);useEffect(()=>{latest.current=project;},[project]);
 async function files(list:File[]){setBusy(true);setError('');try{const data=await Promise.all(list.map(async f=>({name:f.name,base64:await readRfa(f)})));let next=latest.current;for(const f of data)next=addPending(next,f.name,f.base64);onChange(next);}catch(e){setError(validationMessage(e));}finally{setBusy(false);}}
 const active=project.families.find(f=>f.id===selected),filtered=project.families.filter(f=>(!category||f.category===category)&&`${f.name} ${f.fileName}`.toLowerCase().includes(search.toLowerCase()));
 return <><Button variant="outline" onClick={()=>setOpen(true)}>Familias Revit ({project.families.length})</Button><Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v);}}><DialogContent className="families-dialog"><DialogTitle>Familias Revit</DialogTitle><DialogDescription>Biblioteca de esta habitación. Los .rfa se conservan originales; solo Revit puede procesarlos. La vista web usa volúmenes medidos aproximados.</DialogDescription>
 <div className="revit-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)void files(Array.from(e.dataTransfer.files));}}>Arrastra archivos .rfa aquí · máximo 8 MB por archivo<Button disabled={busy} onClick={()=>file.current?.click()}>Importar .rfa</Button><Button disabled={busy} variant="outline" onClick={()=>manifest.current?.click()}>Importar datos procesados</Button><Button variant="outline" onClick={()=>downloadData(JSON.stringify(exportRevit(project),null,2),'mi-habitacion.habitacion.json')}>Exportar para Revit</Button></div>
 <input hidden ref={file} type="file" accept=".rfa" multiple onChange={e=>{const list=Array.from(e.target.files??[]);e.target.value='';void files(list);}}/><input hidden ref={manifest} type="file" accept=".json" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{if(f.size>40_000_000)throw new Error('Máximo 40 MB.');onChange(importManifest(latest.current,JSON.parse(await f.text())));setError('');}catch(e){setError(validationMessage(e));}}}/>
 <p className="helper">Flujo: importar .rfa → descargar originales → procesar con el complemento Windows → importar .revit-families.json. <a href="/revit-integration.zip" download>Descargar código y guía del complemento</a>. Requiere compilación y validación en Revit; no hay conexión automática ni servicio de pago.</p>
 {busy&&<p role="status">Guardando originales…</p>}{error&&<p role="alert" className="error-message">{error}</p>}
 <div className="family-filters"><Input aria-label="Buscar familias" placeholder="Buscar por nombre…" value={search} onChange={e=>setSearch(e.target.value)}/><NativeSelect aria-label="Categoría de familia" value={category} onChange={e=>setCategory(e.target.value)}><NativeSelectOption value="">Todas las categorías</NativeSelectOption>{CATEGORIES.map(c=><NativeSelectOption key={c}>{c}</NativeSelectOption>)}</NativeSelect></div>
 <div className="family-cards">{filtered.map(f=><button key={f.id} className={`family-card ${f.id===selected?'active':''}`} onClick={()=>setSelected(f.id)}>{f.thumbnail?<img src={f.thumbnail} alt={`Previsualización Revit de ${f.name}`}/>:<span className="family-placeholder">RFA<br/>Sin previsualización</span>}<strong>{f.name}</strong><span>{f.status==='pending'?'Pendiente de Revit':`${f.category} · ${f.types.length} tipos · cm`}</span></button>)}</div>{!filtered.length&&<p>No hay familias que coincidan. Importa tus archivos para comenzar.</p>}
 {active&&<FamilyDetails key={active.id} family={active} project={project} onAdded={(p,id,structural)=>{onChange(p);onAdded(id,structural);setOpen(false);}}/>}
 <section className="family-suggestions"><h3>Asistente de sugerencias</h3><p>Reglas locales según tu descripción y las categorías existentes. No usa un modelo de IA ni añade objetos solo.</p><Input aria-label="Describe tu habitación" placeholder="Habitación con zona de estudio" value={brief} onChange={e=>{setBrief(e.target.value);setAsked(false);}}/><Button variant="outline" onClick={()=>setAsked(true)}>Sugerir familias</Button>{asked&&<ul>{suggestions(project,brief).map(s=><li key={s.category}><strong>{s.category}</strong> · {s.reason} {s.families.length?s.families.map(f=><Button key={f.id} variant="ghost" onClick={()=>setSelected(f.id)}>Revisar {f.name}</Button>):'No hay familias procesadas de esta categoría; importa una.'}</li>)}{!suggestions(project,brief).length&&<li>Sin categorías pendientes reconocidas. Prueba «habitación con zona de estudio».</li>}</ul>}</section>
 </DialogContent></Dialog></>;
}
function FamilyDetails({family:f,project,onAdded}:{family:RevitFamily;project:Project;onAdded:(p:Project,id:string,structural:boolean)=>void}){
 const [typeId,setTypeId]=useState(f.types[0]?.id??''),[values,setValues]=useState<RevitBinding['parameters']>({}),[error,setError]=useState('');
 const first=f.types[0]?.dimensionsCm;const [d,setD]=useState({width:String(first?.width??''),depth:String(first?.depth??''),height:String(first?.height??''),x:'100',y:'100',z:f.category==='ventanas'?'90':'0',offset:'50'}),[wall,setWall]=useState<WallId>(roomWalls(project.room)[0].id);
 const type=f.types.find(t=>t.id===typeId),structural=f.category==='puertas'||f.category==='ventanas';
 return <section className="family-details"><h3>{f.name}</h3><p>{f.revitCategory} · {f.sourcePath} · {f.revitVersion||'Versión desconocida'}</p>{f.originalBase64&&<Button variant="outline" onClick={()=>downloadRfa(f.originalBase64!,f.fileName)}>Descargar original .rfa</Button>}{f.notes.map((n,i)=><p key={i} className="helper">{n}</p>)}{f.status==='pending'?<p>Procesa el archivo con el complemento para obtener tipos, parámetros y dimensiones. No se puede añadir aún.</p>:type&&<><label>Tipo<NativeSelect aria-label="Tipo de familia" value={typeId} onChange={e=>{setTypeId(e.target.value);setValues({});const t=f.types.find(t=>t.id===e.target.value);setD({...d,width:String(t?.dimensionsCm?.width??''),depth:String(t?.dimensionsCm?.depth??''),height:String(t?.dimensionsCm?.height??'')});}}>{f.types.map(t=><NativeSelectOption key={t.id} value={t.id}>{t.name}</NativeSelectOption>)}</NativeSelect></label><p>Confirma las medidas reales (cm). La caja web no es una reconstrucción detallada de la familia. El complemento comprobará las dimensiones y avisará si no puede reproducirlas.</p><div className="object-fields">{(structural?['width','height','offset',...(f.category==='ventanas'?['z']:[])]:['width','depth','height','x','y','z']).map(key=>{const k=key as keyof typeof d;return <label key={k}>{{width:'Ancho',depth:'Fondo',height:'Alto',x:'Centro X',y:'Centro Y',z:'Base Z',offset:'Distancia en pared'}[k]} (cm)<Input aria-label={`Familia ${k}`} value={d[k]} onChange={e=>setD({...d,[k]:e.target.value})} inputMode="decimal"/></label>;})}</div>{structural&&<NativeSelect aria-label="Pared de familia" value={wall} onChange={e=>setWall(e.target.value as WallId)}>{roomWalls(project.room).map(({id:w,label})=><NativeSelectOption key={w} value={w}>{label}</NativeSelectOption>)}</NativeSelect>}<Parameters type={type} values={values} onChange={setValues}/>{f.placement==='unsupported'&&<p>Este tipo de hospedaje necesita adaptación en Revit. Puede planificarse como volumen; se informará al exportarlo.</p>}<Button onClick={()=>{try{const placement={wallId:wall} as Placement;for(const key of Object.keys(d) as (keyof typeof d)[]){if(structural&&key==='depth'){placement[key]=1;continue;}if(!/^-?\d+(?:[.,]\d+)?$/.test(d[key]))throw new Error('Completa las medidas y posiciones.');placement[key]=Number(d[key].replace(',','.'));}const result=addFamily(project,f.id,typeId,placement,values);onAdded(result.project,result.id,result.structural);}catch(e){setError(validationMessage(e));}}}>Añadir a habitación</Button></>}{error&&<p role="alert" className="error-message">{error}</p>}</section>;
}
