import {z} from 'zod';
export const CATEGORIES=['puertas','ventanas','camas','mesas','sillas','armarios','escritorios','estanterías','iluminación','decoración'] as const;
export const parameterValue=z.union([z.string().max(2000),z.number().finite(),z.boolean()]);
export const parameterSchema=z.object({key:z.string().min(1).max(200),name:z.string().min(1).max(120),scope:z.enum(['type','instance']),storage:z.enum(['string','integer','double','boolean']),unit:z.enum(['cm','deg','number','text','boolean','unsupported']),readOnly:z.boolean(),value:parameterValue}).strict();
const dims=z.object({width:z.number().finite().positive().max(2000),depth:z.number().finite().positive().max(2000),height:z.number().finite().positive().max(2000)}).strict();
export const typeSchema=z.object({id:z.string().min(1).max(200),name:z.string().min(1).max(200),dimensionsCm:dims.nullable(),dimensionParameters:z.object({width:z.string().nullable(),depth:z.string().nullable(),height:z.string().nullable()}).strict(),parameters:z.array(parameterSchema).max(300)}).strict();
export const familySchema=z.object({id:z.string().min(1).max(200),name:z.string().min(1).max(200),category:z.enum(CATEGORIES),revitCategory:z.string().max(200),fileName:z.string().min(1).max(255).regex(/\.rfa$/i),sourcePath:z.string().max(1000),status:z.enum(['pending','processed']),revitVersion:z.string().max(50),placement:z.enum(['free','wall','unsupported']),unit:z.literal('cm'),originalBase64:z.string().max(12_000_000).regex(/^[A-Za-z0-9+/]*={0,2}$/).refine(s=>s.length%4===0,'Base64 inválido.').nullable(),thumbnail:z.string().max(1_000_000).regex(/^data:image\/png;base64,[A-Za-z0-9+/=]+$/).nullable(),types:z.array(typeSchema).max(100),notes:z.array(z.string().max(1000)).max(100)}).strict().superRefine((f,c)=>{if(new Set(f.types.map(t=>t.id)).size!==f.types.length)c.addIssue({code:'custom',message:'Tipos duplicados.'});if(f.status==='pending'&&f.types.length)c.addIssue({code:'custom',message:'Una familia pendiente no puede declarar tipos procesados.'});for(const t of f.types){if(new Set(t.parameters.map(p=>p.key)).size!==t.parameters.length)c.addIssue({code:'custom',message:'Parámetros duplicados.'});for(const key of Object.values(t.dimensionParameters))if(key&&!t.parameters.some(p=>p.key===key&&p.unit==='cm'&&!p.readOnly))c.addIssue({code:'custom',message:'Mapeo dimensional inválido.'});}});
export const bindingSchema=z.object({familyId:z.string(),typeId:z.string(),parameters:z.record(parameterValue)}).strict();
export const manifestSchema=z.object({format:z.literal('habitacion.revit-families'),version:z.literal(1),families:z.array(familySchema).min(1).max(40)}).strict();
export type RevitFamily=z.infer<typeof familySchema>;
export type RevitBinding=z.infer<typeof bindingSchema>;
export type RevitType=z.infer<typeof typeSchema>;
export function bindingIssues(families:RevitFamily[],binding:RevitBinding|undefined):string[]{if(!binding)return [];const f=families.find(f=>f.id===binding.familyId),t=f?.types.find(t=>t.id===binding.typeId);if(!f||f.status!=='processed'||!t)return ['Referencia de familia o tipo inexistente.'];const errors:string[]=[];for(const [key,v] of Object.entries(binding.parameters)){const p=t.parameters.find(p=>p.key===key);if(!p||p.readOnly||p.unit==='unsupported'){errors.push('Parámetro no editable.');continue;}if((p.storage==='string'&&typeof v!=='string')||(p.storage==='boolean'&&typeof v!=='boolean')||(['integer','double'].includes(p.storage)&&typeof v!=='number')||(p.storage==='integer'&&typeof v==='number'&&!Number.isInteger(v)))errors.push('Tipo de parámetro inválido.');}return errors;}
